### ISSUE TITLE
slack과 연동하기

### ISSUE THREAD

**Issue by HoseokNa** [blackcoffee-dev/CleanClearConfident#3]
# slack과 연동하기

1. slack workspace 런치
2. workspace에 팀원들 초대
3. repository와 slack 연동

**Comment by HoseokNa** [comment]
[slack 초대 링크](https://join.slack.com/t/blackcoffee-frontend/shared_invite/zt-cs0ozl8k-ZxMh_ftlEKJLcbDEE4SvzQ)

**Comment by HoseokNa** [comment]
코멘트 확인

**Comment by HoseokNa** [comment]
코멘트 확인

**Comment by HoseokNa** [comment]
*github-notification 채널에서 아래의 내용들이 자동으로 push 됩니다.*
* New commits
* New pull requests
* New issues
* Code reviews
* Deployment statuses

**Comment by YongHoonJJo** [comment]
> slack 초대 링크

issue 가 closed 되서 못봤었네요 ㅜㅜ
